### ISSUE TITLE
cork create error: failed to create symbolic link

### ISSUE THREAD

**Issue by AnalogJ** [coreos/mantle#958]
Hey,
I'm getting a weird issue when running `cork create` in a VM.

```
    default: 2018-12-12T04:09:29Z cork: Detecting SDK version
    default: 2018-12-12T04:09:31Z cork: Found SDK version 1967.0.0 from remote repo
    default: 2018-12-12T04:09:31Z cork: Downloading SDK version 1967.0.0
    default: 2018-12-12T04:10:38Z sdk: Unpacking SDK into /usr/bin/coreos-sdk/chroot
    default: 2018-12-12T04:12:43Z sdk: Unpacked
    default: ln: failed to create symbolic link '/home/root/trunk': No such file or directory
    default: 2018-12-12T04:12:43Z cork: Create failed: exit status 1
```

I'm using a pretty basic Vagrantfile, and I've tried it on CentOS and Debian with the exact same results

```
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
        v.name = "coreos_builder"
        v.memory = 11264
        v.cpus = 4
    end

    config.vm.provision "shell", path: "provisioner.sh"
end
```

My `provisioner.sh` script looks like:

```
#!/usr/bin/env bash

## Prerequisites

yum install -y \
    ca-certificates \
    curl \
    git \
    bzip2

cd /usr/bin && \
    curl -L -o cork https://github.com/coreos/mantle/releases/download/v0.11.1/cork-0.11.1-amd64 && \
    chmod +x cork && \
    which cork && \
    git config --global user.email "jason@thesparktree.com" && \
    git config --global user.name "Jason Kulatunga"

## Using Cork
# https://coreos.com/os/docs/latest/sdk-modifying-coreos.html

mkdir coreos-sdk
cd coreos-sdk
cork create

#/usr/bin/cork enter && \
#    grep NAME /etc/os-release # Verify you are in the SDK chroot
```

**Comment by dm0-** [comment]
That failure means you're running `cork` as root.  It's intended to be run as a normal user.

**Comment by AnalogJ** [comment]
Hey @dm0- 
Looks like that was the issue. I've updated my provisioner.sh script to the following:
```
#!/usr/bin/env bash

## Prerequisites

# meteor installer doesn't work with the default tar binary
yum install -y \
    ca-certificates \
    curl \
    git \
    bzip2

cd /usr/bin && \
    curl -L -o cork https://github.com/coreos/mantle/releases/download/v0.11.1/cork-0.11.1-amd64 && \
    chmod +x cork && \
    which cork

## Using Cork
# https://coreos.com/os/docs/latest/sdk-modifying-coreos.html=

exec sudo -u vagrant /bin/sh - << 'EOF'
whoami
git config --global user.email "jason@thesparktree.com" && \
git config --global user.name "Jason Kulatunga"

mkdir -p ~/coreos-sdk
cd ~/coreos-sdk
cork create --sdk-version 1911.4.0 --replace

cork enter
grep NAME /etc/os-release

./set_shared_user_password.sh 12345
./setup_board
./build_packages
./build_image

EOF
```

The `cork create command is` working correctly, but the build_packages/build_image commands seem to be failing. Should I open a new issue for that, or can we continue the conversation here?

Logs are as follows:
```

    default: 2018-12-13 06:21:48 (48.1 MB/s) - ‘/build/amd64-usr/var/lib/portage/pkgs/sys-devel/gcc-7.3.0-r3.tbz2.partial’ saved [217541564/217541564]
    default: >>> Emerging binary (1 of 13) sys-apps/gentoo-functions-0.12::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (2 of 13) dev-libs/gmp-5.1.3-r1::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (3 of 13) sys-libs/zlib-1.2.11::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (4 of 13) sys-libs/timezone-data-2018e::coreos for /build/amd64-usr/
    default: >>> Emerging binary (5 of 13) virtual/libiconv-0-r1::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (6 of 13) sys-kernel/linux-headers-4.13::portage-stable for /build/amd64-usr/
    default: >>> Installing (6 of 13) sys-kernel/linux-headers-4.13::portage-stable to /build/amd64-usr/
    default: >>> Recording sys-kernel/linux-headers in "world" favorites file...
    default: >>> Installing (1 of 13) sys-apps/gentoo-functions-0.12::portage-stable to /build/amd64-usr/
    default: >>> Installing (4 of 13) sys-libs/timezone-data-2018e::coreos to /build/amd64-usr/
    default: >>> Installing (2 of 13) dev-libs/gmp-5.1.3-r1::portage-stable to /build/amd64-usr/
    default: >>> Installing (3 of 13) sys-libs/zlib-1.2.11::portage-stable to /build/amd64-usr/
    default: >>> Installing (5 of 13) virtual/libiconv-0-r1::portage-stable to /build/amd64-usr/
    default: >>> Emerging binary (7 of 13) dev-libs/mpfr-3.1.3_p4::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (8 of 13) sys-libs/glibc-2.26-r7::coreos for /build/amd64-usr/
    default: >>> Emerging binary (9 of 13) sys-devel/gcc-config-1.8-r1::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (10 of 13) sys-devel/binutils-config-5-r4::portage-stable for /build/amd64-usr/
    default: >>> Installing (9 of 13) sys-devel/gcc-config-1.8-r1::portage-stable to /build/amd64-usr/
    default: >>> Installing (7 of 13) dev-libs/mpfr-3.1.3_p4::portage-stable to /build/amd64-usr/
    default: >>> Installing (10 of 13) sys-devel/binutils-config-5-r4::portage-stable to /build/amd64-usr/
    default: >>> Installing (8 of 13) sys-libs/glibc-2.26-r7::coreos to /build/amd64-usr/
    default: >>> Recording sys-libs/glibc in "world" favorites file...
    default: >>> Emerging binary (11 of 13) dev-libs/mpc-1.0.1::portage-stable for /build/amd64-usr/
    default: >>> Emerging binary (12 of 13) sys-devel/binutils-2.30-r4::portage-stable for /build/amd64-usr/
    default: >>> Installing (11 of 13) dev-libs/mpc-1.0.1::portage-stable to /build/amd64-usr/
    default: >>> Installing (12 of 13) sys-devel/binutils-2.30-r4::portage-stable to /build/amd64-usr/
    default: >>> Recording sys-devel/binutils in "world" favorites file...
    default: >>> Emerging binary (13 of 13) sys-devel/gcc-7.3.0-r3::portage-stable for /build/amd64-usr/
    default: >>> Installing (13 of 13) sys-devel/gcc-7.3.0-r3::portage-stable to /build/amd64-usr/
    default: >>> Recording sys-devel/gcc in "world" favorites file...
    default: 
    default:  * Messages for package sys-devel/gcc-7.3.0-r3 merged to /build/amd64-usr/:
    default:  * Log file: /build/amd64-usr/var/log/portage/sys-devel:gcc-7.3.0-r3:20181213-062211.log
    default: 
    default:  * If you have issues with packages unable to locate libstdc++.la,
    default:  * then try running 'fix_libtool_files.sh' on the old gcc versions.
    default:  * You might want to review the GCC upgrade guide when moving between
    default:  * major versions (like 4.2 to 4.3):
    default:  * https://wiki.gentoo.org/wiki/Upgrading_GCC
    default: INFO    setup_board: Elapsed time (setup_board): 70m18s
    default: INFO    setup_board: The SYSROOT is: /build/amd64-usr
    default: INFO    update_chroot: Setting up portage...
    default: find: `/mnt/host/source/config/portage/repos': No such file or directory
    default: INFO    update_chroot: Setting up crossdev...
    default: INFO    update_chroot: Updating chroot:
    default: INFO    update_chroot:  chroot version: 1981.0.0+2018-12-13-0512
    default: INFO    update_chroot:  CoreOS version: 1981.0.0+2018-12-13-0622
    default: INFO    update_chroot: Updating basic system packages
    default: >>> Jobs: 0 of 0 complete                           Load avg: 0.84, 2.04, 2.99
    default:  * Switching native-compiler to x86_64-pc-linux-gnu-7.3.0 ...
    default:              [ ok ]
    default: INFO    update_chroot: Updating cross x86_64-cros-linux-gnu toolchain
    default: >>> Jobs: 0 of 0 complete                           Load avg: 0.86, 2.02, 2.98
    default:  * Switching cross-compiler to x86_64-cros-linux-gnu-7.3.0 ...
    default:             [ ok ]
    default: 
    default: >>> No packages selected for removal by rage-clean
    default: INFO    update_chroot: Updating all SDK packages
    default: 
    default: These are the packages that would be merged, in order:
    default: 
    default: Calculating dependencies  
    default: .
    default: ... done!
    default: [ebuild  NS   #] sys-devel/binutils-2.29.1-r1:2.29.1::portage-stable [2.30-r4:2.30::portage-stable] USE="cxx nls -multitarget -static-libs {-test} -vanilla" 28,462 KiB
    default: 
    default: Total: 1 package (1 in new slot), Size of downloads: 28,462 KiB
    default: 
    default: The following mask changes are necessary to proceed:
    default:  (see "package.unmask" in the portage(5) man page for more details)
    default: # required by @selected
    default: # required by @world (argument)
    default: # /mnt/host/source/src/third_party/portage-stable/profiles/package.mask:
    default: # Michał Górny <mgorny@gentoo.org>, Andreas K. Hüttel <dilfridge@gentoo.org>,
    default: # Matthias Maier <tamiko@gentoo.org> (21 May 2017 and later updates)
    default: # These old versions of toolchain packages (binutils, gcc, glibc) are no
    default: # longer officially supported and are not suitable for general use. Using
    default: # these packages can result in build failures (and possible breakage) for
    default: # many packages, and may leave your system vulnerable to known security
    default: # exploits.
    default: # If you still use one of these old toolchain packages, please upgrade (and
    default: # switch the compiler / the binutils) ASAP. If you need them for a specific
    default: # (isolated) use case, feel free to unmask them on your system.
    default: =sys-devel/binutils-2.29.1-r1
    default: 
    default: NOTE: The --autounmask-keep-masks option will prevent emerge
    default:       from creating package.unmask or ** keyword changes.
    default: 
    default: Use --autounmask-write to write changes to config files (honoring
    default: CONFIG_PROTECT). Carefully examine the list of proposed changes,
    default: paying special attention to mask or keyword changes that may expose
    default: experimental or unstable packages.
    default: ERROR   update_chroot: script called: update_chroot '--toolchain_boards=amd64-usr' '--usepkg' '--nousepkgonly' '--getbinpkg' '--jobs=4'
    default: ERROR   update_chroot: Backtrace:  (most recent call is last)
    default: ERROR   update_chroot:   file update_chroot, line 242, called: die_err_trap 'sudo -E ${EMERGE_CMD} "${EMERGE_FLAGS[@]}" coreos-devel/sdk-depends world' '1'
    default: ERROR   update_chroot: 
    default: ERROR   update_chroot: Command failed:
    default: ERROR   update_chroot:   Command 'sudo -E ${EMERGE_CMD} "${EMERGE_FLAGS[@]}" coreos-devel/sdk-depends world' exited with nonzero code: 1
    default: ERROR   setup_board: script called: setup_board '--quiet' '--board=amd64-usr' '--regen_configs' '--usepkg' '--nousepkgonly' '--getbinpkg' '--notoolchainpkgonly' '--jobs=4'
    default: ERROR   setup_board: Backtrace:  (most recent call is last)
    default: ERROR   setup_board:   file setup_board, line 211, called: die_err_trap '"${SRC_ROOT}/scripts"/update_chroot ${UPDATE_ARGS}' '1'
    default: ERROR   setup_board: 
    default: ERROR   setup_board: Command failed:
    default: ERROR   setup_board:   Command '"${SRC_ROOT}/scripts"/update_chroot ${UPDATE_ARGS}' exited with nonzero code: 1
    default: ERROR   setup_board:   (Note bash sometimes misreports "command not found" as exit code 1 instead of 127)
    default: ERROR   build_packages: script called: build_packages (args unknown, no debug available)
    default: ERROR   build_packages: Backtrace:  (most recent call is last)
    default: ERROR   build_packages:   file build_packages, line 124, called: die_err_trap '"${SCRIPTS_DIR}"/setup_board --quiet --board=${FLAGS_board} "${UPDATE_ARGS[@]}"' '1'
    default: ERROR   build_packages: 
    default: ERROR   build_packages: Command failed:
    default: ERROR   build_packages:   Command '"${SCRIPTS_DIR}"/setup_board --quiet --board=${FLAGS_board} "${UPDATE_ARGS[@]}"' exited with nonzero code: 1
    default: ERROR   build_packages:   (Note bash sometimes misreports "command not found" as exit code 1 instead of 127)
    default: INFO    build_image: Checking build root
    default: INFO    build_image: Checking /build/amd64-usr
    default: /usr/share/gcc-data/x86_64-cros-linux-gnu/7.3.0/fix_libtool_files.sh: /bin/sh does not exist
    default: /usr/share/gcc-data/x86_64-cros-linux-gnu/7.3.0/c89: /bin/sh does not exist
    default: /usr/share/gcc-data/x86_64-cros-linux-gnu/7.3.0/c99: /bin/sh does not exist
    default: /usr/bin/c89: /bin/sh does not exist
    default: /usr/bin/sotruss: /bin/bash does not exist
    default: /usr/bin/gcc-config: /bin/bash does not exist
    default: /usr/bin/tzselect: /bin/bash does not exist
    default: /usr/bin/xtrace: /bin/bash does not exist
    default: /usr/bin/ldd: /bin/bash does not exist
    default: /usr/bin/c99: /bin/sh does not exist
    default: /usr/bin/catchsegv: /bin/sh does not exist
    default: /usr/bin/binutils-config: /bin/bash does not exist
    default: /usr/sbin/coreos-tmpfiles: /bin/bash does not exist
    default: /usr/sbin/fix_libtool_files.sh: /bin/sh does not exist
    default: WARNING build_image: test_image_content: Failed #! check
    default: Traceback (most recent call last):
    default:   File "/mnt/host/source/src/scripts/build_library/check_root", line 299, in <module>
    default:     sys.exit(main())
    default:   File "/mnt/host/source/src/scripts/build_library/check_root", line 290, in main
    default:     ok = func() and ok
    default:   File "/mnt/host/source/src/scripts/build_library/check_root", line 261, in check_symlink
    default:     error("broken link: %s", path)
    default:   File "/mnt/host/source/src/scripts/build_library/check_root", line 267, in error
    default:     sys.stderr.write(output.red(fmt % args))
    default: LookupError: unknown encoding: ascii
    default: ERROR   build_image: test_image_content: Failed symlink check
    default: This system is not affected by any of the listed GLSAs
    default: ERROR   build_image: script called: build_image (args unknown, no debug available)
    default: ERROR   build_image: Backtrace:  (most recent call is last)
    default: ERROR   build_image:   file build_image, line 74, called: die_err_trap 'return $returncode' '1'
    default: ERROR   build_image: 
    default: ERROR   build_image: Command failed:
    default: ERROR   build_image:   Command 'return $returncode' exited with nonzero code: 1

```
